format_version: 10
pipelines:
  tools-tf-Destroy:
    group: tools-tf-Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-214f6fa:
        git: git@github.com:cDevOps78/tools-automation.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            job1:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - terraform.sh
                      - destroy
                    command: bash
                    run_if: passed