- name: Install yum-utils
  ansible.builtin.shell: yum install -y yum-utils

- name: Adding yum repo
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Installing vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: To start vault service
  ansible.builtin.systemd_service:
    name: vault
    state: started
    enabled: yes