- name: Download and extract the prometheus content
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    owner: bin
    group: bin
    remote_src: yes

- name: copy prometheus service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: copy prometheus.yaml file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-{{ version }}.linux-amd64/prometheus.yml

- name: To start prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon-reload: yes
    enabled: yes

