
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093


rule_files:
# - "first_rules.yml"
# - "second_rules.yml"


scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ec2-nodes"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: tag:monitor
            values: ["yes"]
    relabel_configs:
      - source_labels:
          - '__meta_ec2_tag_Name'
        target_label: "instance"
      - source_labels:
          - '__meta_ec2_instance_type'
        target_label: "instance_type"
      - source_labels:
          - '__meta_ec2_private_ip'
        target_label: "privateIP"


